export const AWSINFO = {
  ACCESS_KEY_ID: process.env.REACT_APP_AWS_ACCESS_KEY_ID,
  SECRET_ACCESS_KEY: process.env.REACT_APP_AWS_ACCESS_KEY_ID,
  UPLOAD_REGION: process.env.REACT_APP_AWS_UPLOAD_REGION,
  S3_UPLOAD_BUCKET: process.env.REACT_APP_AWS_S3_UPLOAD_BUCKET,
};
